sudo: required
services:
  - docker

before_install:
  - docker build -t namanblock8/docker-react -f Dockerfile.dev .

script:
  - docker run namanblock8/docker-react npm run test-ci

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-371243547502"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"